apiVersion: v1
kind: Service
metadata:
  name: vaadin-build-demo
  labels:
    app.kubernetes.io/name: vaadin-build-demo
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/name: vaadin-build-demo
